version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_demologin
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: demologin
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always

  backend:
    build: .
    container_name: backend_demologin
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/demologin?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    restart: always

volumes:
  mysql-data:
    driver: local
